### PR TITLE
fix 'super' object has no attribute 'coerce' error

### PR DESCRIPTION
**Pull request by casualuser**
repeat fix https://github.com/edelooff/sqlalchemy-json/issues/10 for NestedMutableDict and NestedMutableList

### CODE REVIEW

**Comment by akshay-joshi** [comment]
Any idea when this PR gets merged as we are using this in the development of pgAdmin4 but facing the same issue.
When will the new release?

**Comment by akshay-joshi** [comment]
@edelooff Can you please update, so we can decide to wait for the release or find some other way?

**Comment by edelooff** [comment]
@akshay-joshi apologies for the terrible delay. I'd be happy to merge this fix, but could you provide a sample case of this failing, so that regressions can be prevented.

For reference, the following test works for me locally:

```python
class Dummy(Base):
    __tablename__ = "dummy"
    id = Column(Integer, primary_key=True)
    content = Column(NestedMutableJson)


def test_nulls(session):
    session.add(Dummy(content={"foo": "bar"}))
    session.commit()

    element = session.query(Dummy).one()
    assert element.content is not None
    element.content = None
    session.commit()
    assert element.content is None
```

**Comment by edelooff** [comment]
Resolved with the [v0.6.0 release](https://pypi.org/project/sqlalchemy-json/0.6.0/).

**Pull request closed without merging**
